### ISSUE TITLE
real newbie here - can I use only one robot?

### ISSUE THREAD

**Issue by Poly44** [Opentrons/covid19#11]
Hi, I have zero experience with pippetting robots and such. I am hoping to get an OT-2 with a suitable configuration for our needs. I was wondering if I could attempt to combine configurations for Station A and Station B (Sample prep + RNA extraction) in one single robot.

**Comment by SyntaxColoring** [comment]
Hey there! 👋 

In principle, yes. The OT-2s are flexible; stations can be split or combined.

But the effectiveness will depend on a few things. Do you have a specific kit you're looking to automate? How are your samples are coming in? How much work are you willing to do manually?

The limiting factor will probably be the pipette setup. The OT-2 can have two [Opentrons pipettes](https://opentrons.com/pipettes) attached at once. Which two pipettes are the best choice changes depending on how far along you are in the protocol.

**Comment by Poly44** [comment]
Thank you very much for your answer! I'll keep thinking then. Cheers!

**Comment by SyntaxColoring** [comment]
I'm going to close this issue for now, to keep things tidy. But feel free to leave more replies, and we'll respond.
