### ISSUE TITLE
Why we need 3 separate robots？ Is that possible that we can use one robot plus PCR machine for the entire process?

### ISSUE THREAD

**Issue by WenhaoDeng** [Opentrons/covid19#12]
Why we need 3 separate robots？ Is that possible that we can use one robot plus PCR machine for the entire process?

**Comment by SyntaxColoring** [comment]
Hey @WenhaoDeng, would you mind reaching out to info@opentrons.com with that question?

We don't actively use this repository anymore, so what you see here doesn't necessarily represent our most up-to-date practices for using the OT-2 for COVID stuff.

Thanks!
